# Generated by Django 3.0.3 on 2020-07-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Faculty', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Fee', models.FloatField()),
                ('Duration', models.IntegerField()),
            ],
        ),
    ]
